language: java
script: mvn package
cache:
  directories:
  - "$HOME/.m2"

branches:
  only:
  - "/^(feature|bugfix)\\/SCC-[0-9]+.*$/"
  - "/^(release)\\/.*$/"
  - bat/develop
  - main

# Install dependencies
before_install:
  - sudo rm -Rf terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo rm -Rf terraform
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip

deploy:

# SBX - modify CF_ENVIRONMENT as required
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=sbx2 bash ./deploy.sh
  on:
    all_branches: true
    condition: "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^(feature|bugfix)\\/SCC-[0-9]+.*$"

# DEVELOP    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=dev bash ./deploy.sh
  on:
    branch: bat/develop
    
# INT (SIT)    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=int bash ./deploy.sh
  on:
    branch: release/int

# NFT    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=nft bash ./deploy.sh
  on:
    branch: release/nft
    
# UAT    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=uat bash ./deploy.sh
  on:
    branch: release/uat
    
# REF    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=ref bash ./deploy.sh
  on:
    branch: release/ref

# PRE    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=pre bash ./deploy.sh
  on:
    branch: release/pre    

# PRD    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=prd bash ./deploy.sh
  on:
    branch: release/prd    

# WARNING! Do NOT use the --add flag of travis cli encrypt - it removes all formatting and comments
env:
  global:
  # AWS_ACCESS_KEY_ID 
  - secure: "bQvUi4ytpvq0VGBlK8QLJvICl12IVk6mGK+YCd9zquiuIJv0lSkvvhKY0RF7k0SqLvl1M22D7rvlfgO5EilDmbfrXq2wkngDkwjNZKntoxmICGySaYOCtTH1pF9asPPY4tyb6jJYR8BfFuDcXk205TknP9yGoPAf8gQtQ4YnKPIpxQip0ZB3GwGLDOpTLCZpbCN3QOD+JZKIRuWmSiVxef2C6/kmbkvzdyAKQp6dBmuu7ntCW2UQ6hw+8SnZ1qOkuhqXjdZUzRz//2q+DumJHwdU57+WK8RnZmmVLaHK3xkq1SENYAnlXOBkSy5vMcDEvylTeStM6oKqBgIhZ55zQG38/op4WmtM4U+hUCCygqEGGy+ufnW3yZG8hJ9myzDxFjiANLMr0NlawWISYw0rUej/DCRw1IF7XQDuiFmQwgT2kDGiQlofphK2EGL7z237f993Ety+fBn4F1fWXW2eHrrcZKJYQ96OdM3FO3IliNySS1kwFSl4OMvKaBteZZM8mQwnXBWD//xrMcB1KhTVpt9zbToPKxlImRWlWGdHUNuymktwzFdLMQUF7kbHT0RnoOBUFdvIb6bESxJ6/jVRnd+NkfW/GaJdsCq1KwlkEiycw1kSNPfWT9IvI6OILjtYDn5vFpEbq20Cl7pf2d1ZO5QECf9VRQHr+T/Q/cTBNY8="
  # AWS_SECRET_ACCESS_KEY
  - secure: "GTQe6fNkVmRpNso7MCDKEd/X6rCfKQWgbaGmc4WeY+/WtFe3CQ+6wADNwrlC5NVMVOOWTtr05FqzZFubQX1OC/IrN23pHiCpKrDHhNq8BMgdzu7KRhgJfk1f07yynn/pqfNc7eW5mSpLfvzt3hpZeZI9PrLidrQnk8kSdhd/gCg9qMvlLNGMMXUpbFhM8d84PPU6VLmv5Mb5iliSZJJioQ3nRnvlaESsIUb9ldDNbCNd5AK7GIEcmqisKaEaGxjWOUEL/U5g3ZpyAecrFD2UycMrTD6s7khFYPP4PMmteOmRE//WaMqkaqwagwHhsWsXSNnVEtJsPGbHTdgoo9k8pBDT1KR6Fl/iIuQpAprVzcbGLCzZdAiGmZ8hDuoBiieOKRgjQRXEWR9Frmp6w/TSku1PDG+XLwkfLSCtUNGGE2aCK1cIo2sJXoHx8KIzeKXl1HV5175rYzrHFYn8MA6V4Vxmk4UHTNumZvN3xYuwWxnP7xA9u/DO20ekuIZfODmhAuNYTrNsbAWm0+Cd0Jw1X25wbhJaXeRKEx/dSQy5K+EkNc4ZBU8se58CxVKmyK4U5O+KxoSbDx5iaSnuCp7Momp4q7fzLUVQiTrJ++4xtwLWIW3rdxRszdQPBKSyY2zSnT+GeX9STI9622ASCJN6xfohoNEq0lN7Gn5HwIA4whs="
  # S3_STATE_BUCKET_NAME
  - secure: "k79+FO2aIlYkKqAPbvnmNYpi2y3TMtmrpUAKS4w3VfEttyIy2YwMorF2YnjOWgDIj48N1lIPIWvu0QNTJNboOh7/hWXRgPaP15A8W7aoFeOHmySKqU9MzxZ/M7IKPz+m5fk3aPxmwYBQ3PN5uA+b9om5xro50haKsz4Ej9pKk+VEX1WmED8rQ+iz2eaIvca+DPVOn/zQmbNUHKG4+hsRAj7QTBKs5v8pdbquJG8H9VckBXSH4A54fOJuqjNvNcqm4mDJ3k+eAkb+iN7MxwiImOgOEczAjtRW696vbpVi4O3X73y4qBq1tOss0CjG+EiE+l2aQ1IjEtCe0HZMjl7455PtW5my2ioYAMWULeWx6fWSrL1fulpBep1tck8H1x/UtoSbA9Ez84qXbRfydKzKIjc/z46y/vIawl0R8S6meIM0wjfwJ5OKuWJYzo4O+uaZCEdHos+8mBLACBdawIb3UrzyYBrKcNJeiAQrQh2n0QR9FYcV7xs4kYwgnbAAp0BNdOArD0JROEqfk29lWfsPBnHBwJLyGJ9Bl1BL270q2pIY3+QquZjPpdSlxij5TLwn0dJUfC500yta0peDn/sv9Yl4HAwsN2ppsWak2HrFT1zgyYj5B65ZR4JUqwl649+0JpclwzrsGCy7fuZYzMeSTjkGgMJ3cMPXR6+iBLkfNmg="
  # DDB_LOCK_TABLE_NAME
  - secure: "JxJ+LHacssw9sGDtkPOOVE2FCMv11VGy0Hyntrw7oW/qid/8IYOxiqSkozJu3oYAm4p5RmapwoHWdQP1JTaGBgy8ef9/guZRdPDX9stIqj0LQGvkpafvtgNsYipYg9IyJ7hhIqGnmIdIkDXvsP6U6jLlI66GXM4ufyFbVJujGAf8xwkh3kwxWX4qgHgBsGGVGB5F+JmW10Lpof+vsPx7XE3/0wLyAikQiRgTqJaQzQMlc9UbI1SxbPSf4jdx1dgXkiBMRNTDfU2ERBeFUVjdfLIwM8evaDiSZeLMROnYtAA/TddsvdJ01gWpyvKQJ8UG+y1RSQY5PNO8Z2DzcVTUD7o4e87+LPOigPS+P8BKuCrB3auITq4lsY+iLT60+SxyfWgXyGvv99EJpM7taEeTHVSzPG9fqoYw4KXDUDIkj2cgQ4/n/1ZuONhUTg/dzPtbVggtkm3bgByIgGur3pUVtY81sPQbKMfssWz76UM/L9jt8ijGEJEutL9G8h4GZ2n1vfb21NDulVZyBcZrmhH8fZyY+79qlWk/mQmHjVE8oJzu5jKXtiHf9E1jTvBYJSdNfK7yEu5ZKatqqOOkPOPjV1ZczLPYu9VSMm7nsovxaYU03kcWxHuzyweQlqQXo4DwG553qCexzNghO/Q3hsbXsZuAHXKT4HkDYdF9yM1z5uM="
  # CF_USERNAME
  - secure: "a9kqosKnC7OKPbR4Lw00RCZXqQ8p3v82nbIBXi/TAvbHc2iCZAou4Ik/cGI6EWYYoTwKvB1YnSvJJpSG82kSEOoVXS4kVLSXlNAY/iRl8ehEXrawHPJnunslvAyZYp6Y2wpC4Rj0h58hRYkMcgJzGKbkOkPdS6Qhxq2bNv9Vr6tsEYvRmFflnS6DHFAydKv1OXOiyeBqySMaeu6oazd6ZfFOlpEGgOvM7gQDt+JE2AUGEmzyHvDFPI/vISKkdfRa2AI4WCm6E10Ubj/4ShMlhIZh0iFBuHIg6m5XYEHfKn4InVojrNwgeiTWbsPYjzeix4cMOsAAovkqStw/u+lDIqSG24FtV6xiDYPW5G9tlWUyt5VC8xPhMbJE5st9v8wdbfCgAK6shxgIDZ/4609fKF1qn/EfP1sOmVF6kOuMNNolSjMKtRs89kC69OHg2PaxKtE8jfDTXyXfetRgT0a76hTrp2D0MmARA+9elj4BFdDu5pLiz1byRaCNxahS9upc72kkMDB3vxou5IUVlXVW6JEYZO5MvgzqWEQxtu5wZmxCnBTGQvqs29I2X/l6kl2Ej7442TTHwqGKcpG2iQzfQYKUa/PIn+5z3yh7gqiw0WbCqBc3q2GLyPifJdr1YJ8gHphHPXKQ++OJpfiLJePnpGyKfL8r30u0YSLWUXplhvY="
  # CF_PASSWORD
  - secure: "W/eP+yEpgZ/o8ck2dcVYI6Ck9net+wHJGRfaQGLdeVfua2XlfGQd5h95L2pjqefNRhrZYZqsyScDEEHnmpYuS19U94z2C/P8JOSF2tv+7ZXS3FNLcHMu064/7yvsb+fCwOzAACF9oUhz+HE8eP0zo2qhVXAwEO0RNNN/L9+Xt43NM3j2MpFqO05oh9yE4skVC/rXop7anE4XP5hfaYypQsWA/yWBqvwUjTzbyEaUo7AO9Ko7/t536FftsvGz5BtfScbWAyh5TkHP10TOmTxAIZra/GSx0yzbAr/Q/5o1OiuzngNvVE65bAL89CKVbXDEloj7pbxbDbUNzrVztvHybhM0inMnbnCf7K8ntlo/drDMBjK9Ug8KiDsHXrUvTJNuTSFBRui/6tV+01D9ywYHdGjJ6m2hp4ivBWULaFGkg6OwL4aVsJZQOK1DW6PWTO1e1rJfywT74IABg7k5NhjvYEE1CZzrEB/FSeDcjq5CM6nIKUjItLdHjzeLsMwwCZTUxUL2T0vWfWFHPpT2haMAMk4YLY3z5lQ062rSrgHwf0d2aEVZG26t1uGCVIrM+FYQ2SM5dw5PZonsqkqHv+8oOHjWef8ScibBTwCAVQ9Y7UqB3Z+YcwFIekjX1KotnPbypdae58mMMyd2imuXPng5d3JkhwWP42LwNFc3RPqF+ck="
  - TF_VERSION=1.0.5
