language: java
script: mvn package
cache:
  directories:
  - "$HOME/.m2"

branches:
  only:
  - "/^(feature|bugfix)\\/SCC-[0-9]+.*$/"
  - "/^(release)\\/.*$/"
  - bat/develop
  - main

# Install dependencies
before_install:
  - sudo rm -Rf terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo rm -Rf terraform
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip

deploy:

# SBX - modify CF_ENVIRONMENT as required
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=sbx2 bash ./deploy.sh
  on:
    all_branches: true
    condition: "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^(feature|bugfix)\\/SCC-[0-9]+.*$"

# DEVELOP    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=dev bash ./deploy.sh
  on:
    branch: bat/develop
    
# INT (SIT)    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=int bash ./deploy.sh
  on:
    branch: release/int

# NFT    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=nft bash ./deploy.sh
  on:
    branch: release/nft
    
# UAT    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=uat bash ./deploy.sh
  on:
    branch: release/uat
    
# REF    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=ref bash ./deploy.sh
  on:
    branch: release/ref

# PRE    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=pre bash ./deploy.sh
  on:
    branch: release/pre    

# PRD    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=prd bash ./deploy.sh
  on:
    branch: release/prd    

# WARNING! Do NOT use the --add flag of travis cli encrypt - it removes all formatting and comments
env:
  global:
  # AWS_ACCESS_KEY_ID 
  - secure: "LEaH1x5TOvzvjjRdZIbLp+fm/ABn1SnfZKZb2wNDSVfawgBwfKCnSb3FhU1vWarjdzSMikSVuvbLkxCS+q1v7agKYoNQ23E169RToZnLnQPg/QxAQdP7R4XZNEBMYDJjSWHonY3V13K2dlW659WOk539Eunlgsj+zkwcrvY9QU35fxYgfXi/DQWhoXFoq3NHNyEpsaen8a6J7MVZmeL6Hg7HKprV5y+wrKnpu1ITQPtaLdnD9+bJ2aOt/VvCWxamafHQrb30982YAAaPnuLuaO5eMYKs5pum2AKrylEhIB5otkjh5UKg5yJrDparOfxyk9bTgkBJeqSwkEKAi6121bprPXucDquT1NfqSQfUBdmI9sf5TFpi6n/UjgwIAhzUxv6NZf2o6M96B2PVpX6TjJmLRV0GgtXUeEhZIL4OmxEAlB0eUsTxYpawHloZiF55w/jMwtI+w+qGeWGm7aLQOZjtYAv+XuJva6rC2h3TMtPS8itvccjhHNWrQQqkJrF/QMMibZ5AMjLhsk1LlQ1+mCo8qZeoCtUyHHwmgJenxZ+m/YGrCb9M2afruUwnywG5pwh1pbUp+xk6t5kLqLcGossoGe+h/AU1pRh3bpqNihWOJru09zER8hDi1W9dJ+n1I9BQXUDG8lMbc9rac1Pe4cG2MpJHEyOy66Ggi3BAxzQ="
  # AWS_SECRET_ACCESS_KEY
  - secure: "RaRmC7jm+Y6u+GUJYdJw8zSJ6ZL7zopj/y6YCvZEKliRI12jJP+IuPz3aq6Lp7ypacG2VhXxzCofXwrQhePsOonSqj5jgUxJbw7/ekBQc9647zYciOIygVbGNP9an8KKwquFmGxUXtl3G8jSQ8plYtPoHB065Nx/W/vHPkfLVEJG82fBHrY37/ymhtXfzIMymWcHq166qgN0qqbm1IrZelJlTCwFDRg8iL21vHm1efTZPqhKJBRFtMTYB9+k5oZxUK+MH4f1iGZIoaBbcI5gZkh4SBYWUlFeT6bG1yO5ZsIc0f2CblkusMGhHswT0Mc4lcd65e6L43vPbYpYGgRfmBH2xOzQxVqA+tu86CMuDKAhiC1tVJKRMJ96dZ5mj9paaOu6yFuFTpJmA8k8ndZDBep8SQc+IBQezlkC0biGfX6IvWPPllQqj2j3pUBLEE0vyDDajcv7ei50KFR1dklO3hhgX46unLSUBFhhevgNGT1sHNB8HarHI09vlsdyBWyKvj3qttrCSlbfJa4b2pEMjSnsIQoeZBRv9YehYgKESe8pU47POV3rvTVpw1xuLlnYHM/H+Ntxb87fVabRFwLzOo782WpU6wYKEygva7tyqVRzEntmo6Q3fRqZu1KuHXBhMmWpeGEPkTkuIco/dwgjKZWnELB7xiC1ue+Id8JQu2M="
  # S3_STATE_BUCKET_NAME
  - secure: "k79+FO2aIlYkKqAPbvnmNYpi2y3TMtmrpUAKS4w3VfEttyIy2YwMorF2YnjOWgDIj48N1lIPIWvu0QNTJNboOh7/hWXRgPaP15A8W7aoFeOHmySKqU9MzxZ/M7IKPz+m5fk3aPxmwYBQ3PN5uA+b9om5xro50haKsz4Ej9pKk+VEX1WmED8rQ+iz2eaIvca+DPVOn/zQmbNUHKG4+hsRAj7QTBKs5v8pdbquJG8H9VckBXSH4A54fOJuqjNvNcqm4mDJ3k+eAkb+iN7MxwiImOgOEczAjtRW696vbpVi4O3X73y4qBq1tOss0CjG+EiE+l2aQ1IjEtCe0HZMjl7455PtW5my2ioYAMWULeWx6fWSrL1fulpBep1tck8H1x/UtoSbA9Ez84qXbRfydKzKIjc/z46y/vIawl0R8S6meIM0wjfwJ5OKuWJYzo4O+uaZCEdHos+8mBLACBdawIb3UrzyYBrKcNJeiAQrQh2n0QR9FYcV7xs4kYwgnbAAp0BNdOArD0JROEqfk29lWfsPBnHBwJLyGJ9Bl1BL270q2pIY3+QquZjPpdSlxij5TLwn0dJUfC500yta0peDn/sv9Yl4HAwsN2ppsWak2HrFT1zgyYj5B65ZR4JUqwl649+0JpclwzrsGCy7fuZYzMeSTjkGgMJ3cMPXR6+iBLkfNmg="
  # DDB_LOCK_TABLE_NAME
  - secure: "JxJ+LHacssw9sGDtkPOOVE2FCMv11VGy0Hyntrw7oW/qid/8IYOxiqSkozJu3oYAm4p5RmapwoHWdQP1JTaGBgy8ef9/guZRdPDX9stIqj0LQGvkpafvtgNsYipYg9IyJ7hhIqGnmIdIkDXvsP6U6jLlI66GXM4ufyFbVJujGAf8xwkh3kwxWX4qgHgBsGGVGB5F+JmW10Lpof+vsPx7XE3/0wLyAikQiRgTqJaQzQMlc9UbI1SxbPSf4jdx1dgXkiBMRNTDfU2ERBeFUVjdfLIwM8evaDiSZeLMROnYtAA/TddsvdJ01gWpyvKQJ8UG+y1RSQY5PNO8Z2DzcVTUD7o4e87+LPOigPS+P8BKuCrB3auITq4lsY+iLT60+SxyfWgXyGvv99EJpM7taEeTHVSzPG9fqoYw4KXDUDIkj2cgQ4/n/1ZuONhUTg/dzPtbVggtkm3bgByIgGur3pUVtY81sPQbKMfssWz76UM/L9jt8ijGEJEutL9G8h4GZ2n1vfb21NDulVZyBcZrmhH8fZyY+79qlWk/mQmHjVE8oJzu5jKXtiHf9E1jTvBYJSdNfK7yEu5ZKatqqOOkPOPjV1ZczLPYu9VSMm7nsovxaYU03kcWxHuzyweQlqQXo4DwG553qCexzNghO/Q3hsbXsZuAHXKT4HkDYdF9yM1z5uM="
  # CF_USERNAME
  - secure: "a9kqosKnC7OKPbR4Lw00RCZXqQ8p3v82nbIBXi/TAvbHc2iCZAou4Ik/cGI6EWYYoTwKvB1YnSvJJpSG82kSEOoVXS4kVLSXlNAY/iRl8ehEXrawHPJnunslvAyZYp6Y2wpC4Rj0h58hRYkMcgJzGKbkOkPdS6Qhxq2bNv9Vr6tsEYvRmFflnS6DHFAydKv1OXOiyeBqySMaeu6oazd6ZfFOlpEGgOvM7gQDt+JE2AUGEmzyHvDFPI/vISKkdfRa2AI4WCm6E10Ubj/4ShMlhIZh0iFBuHIg6m5XYEHfKn4InVojrNwgeiTWbsPYjzeix4cMOsAAovkqStw/u+lDIqSG24FtV6xiDYPW5G9tlWUyt5VC8xPhMbJE5st9v8wdbfCgAK6shxgIDZ/4609fKF1qn/EfP1sOmVF6kOuMNNolSjMKtRs89kC69OHg2PaxKtE8jfDTXyXfetRgT0a76hTrp2D0MmARA+9elj4BFdDu5pLiz1byRaCNxahS9upc72kkMDB3vxou5IUVlXVW6JEYZO5MvgzqWEQxtu5wZmxCnBTGQvqs29I2X/l6kl2Ej7442TTHwqGKcpG2iQzfQYKUa/PIn+5z3yh7gqiw0WbCqBc3q2GLyPifJdr1YJ8gHphHPXKQ++OJpfiLJePnpGyKfL8r30u0YSLWUXplhvY="
  # CF_PASSWORD
  - secure: "W/eP+yEpgZ/o8ck2dcVYI6Ck9net+wHJGRfaQGLdeVfua2XlfGQd5h95L2pjqefNRhrZYZqsyScDEEHnmpYuS19U94z2C/P8JOSF2tv+7ZXS3FNLcHMu064/7yvsb+fCwOzAACF9oUhz+HE8eP0zo2qhVXAwEO0RNNN/L9+Xt43NM3j2MpFqO05oh9yE4skVC/rXop7anE4XP5hfaYypQsWA/yWBqvwUjTzbyEaUo7AO9Ko7/t536FftsvGz5BtfScbWAyh5TkHP10TOmTxAIZra/GSx0yzbAr/Q/5o1OiuzngNvVE65bAL89CKVbXDEloj7pbxbDbUNzrVztvHybhM0inMnbnCf7K8ntlo/drDMBjK9Ug8KiDsHXrUvTJNuTSFBRui/6tV+01D9ywYHdGjJ6m2hp4ivBWULaFGkg6OwL4aVsJZQOK1DW6PWTO1e1rJfywT74IABg7k5NhjvYEE1CZzrEB/FSeDcjq5CM6nIKUjItLdHjzeLsMwwCZTUxUL2T0vWfWFHPpT2haMAMk4YLY3z5lQ062rSrgHwf0d2aEVZG26t1uGCVIrM+FYQ2SM5dw5PZonsqkqHv+8oOHjWef8ScibBTwCAVQ9Y7UqB3Z+YcwFIekjX1KotnPbypdae58mMMyd2imuXPng5d3JkhwWP42LwNFc3RPqF+ck="
  - TF_VERSION=1.0.5
