server:
  port: 9010
  error:
    path: "/error"

caching:
  primary:
    # 1 hour
    cacheLength: 3600
    heapSize: 50
  secondary:
    # 15 mins
    cacheLength: 900
    heapSize: 100

logging:
  level:
    uk.gov.crowncommercial.dts.scale: INFO
    org.springframework: INFO
    org.hibernate: INFO

spring:
  jackson:
    default-property-inclusion: non-empty
    property-naming-strategy: LOWER_CAMEL_CASE 
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
      format-sql: true
      cache:
        use_second_level_cache: true
        use_query_cache: true
        region:
            #required - classpath to cache region factory.
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    properties:
      hibernate:
        dialect: uk.gov.crowncommercial.dts.scale.service.agreements.config.PostgreSQL10JsonDialect

---
spring:
  profiles: local
  datasource:
    # Credentials via environment variables ONLY.
    url: jdbc:postgresql://localhost:5432/agreements?currentSchema=ccs_agreements
  jpa:
    show-sql: false
    
server:
  servlet:
    context-path: /agreements-service
